# For a complete example look at:
# https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml
extension:
  - 'js'
  - 'ts'
require:
  - 'ts-node/register'
spec:
- 'test/**/*.test.ts'
trace-warnings: true
watch: false
watch-files:
  - 'lib/**/*.ts'
  - 'test/**/*.ts'
